solidc: include/cache.h File Reference
cache.h File Reference
Cache management utilities for performance optimization.
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
Typedefs
typedef struct cache_s cache_t
Functions
cache_t * cache_create (size_t capacity, uint32_t default_ttl)
void cache_destroy (cache_t *cache)
const void * cache_get (cache_t *cache, const char *key, size_t key_len, size_t *out_len)
void cache_release (const void *ptr)
bool cache_set (cache_t *cache, const char *key, size_t key_len, const void *value, size_t value_len, uint32_t ttl_override)
void cache_invalidate (cache_t *cache, const char *key)
void cache_clear (cache_t *cache)
size_t get_total_cache_size (cache_t *cache)
size_t get_total_capacity (cache_t *cache)
bool cache_save (cache_t *cache_ptr, const char *filename)
bool cache_load (cache_t *cache_ptr, const char *filename)
Detailed Description
Cache management utilities for performance optimization.
Definition in file cache.h.
Typedef Documentation
cache_t
typedef struct cache_s cache_t
Opaque handle to the cache. Implementation details are hidden in cache.c to allow alignment optimizations without breaking ABI.
Definition at line 25 of file cache.h.
Function Documentation
cache_clear()
void cache_clear (cache_t * cache_ptr)
Clears all entries from the cache index.
Removes all entries from the cache. Decrements reference counts on all entries.
Definition at line 564 of file cache.c.
cache_create()
cache_t * cache_create (size_t capacity, uint32_t default_ttl)
Creates a new cache.
Parameters
capacity Total maximum number of entries (distributed across shards).
default_ttl Default time-to-live in seconds.
Returns
Pointer to new cache, or NULL on failure.
Creates a new cache with the specified capacity and default TTL.
Parameters
capacity Total capacity across all shards (0 = default 1000)
default_ttl Default time-to-live in seconds (0 = CACHE_DEFAULT_TTL)
Returns
Pointer to cache on success, NULL on allocation failure
Definition at line 336 of file cache.c.
cache_destroy()
void cache_destroy (cache_t * cache_ptr)
Destroys the cache and frees resources. Note: Zero-copy references held by users remain valid until cache_release() is called, even after the cache object is destroyed.
Destroys the cache and frees all associated memory. Decrements reference counts on all entries.
Definition at line 384 of file cache.c.
cache_get()
const void * cache_get (cache_t * cache_ptr, const char * key, size_t klen, size_t * out_len)
Zero-Copy Retrieval.
Parameters
cache The cache handle.
key The lookup key.
key_len The length of the key.
out_len Pointer to store the size of the retrieved value.
Returns
Pointer to the value data, or NULL if not found.
Note
YOU MUST CALL cache_release() on the returned pointer when done.
Retrieves a value from the cache by key.
The returned pointer is reference-counted. Caller must call cache_release() when done. Automatically checks expiration and invalidates expired entries.
Parameters
cache_ptr The cache instance
key The key string (null-terminated)
out_len Output: length of the value (can be NULL)
Returns
Pointer to value on success, NULL if not found or expired
Definition at line 414 of file cache.c.
References cache_invalidate().
cache_invalidate()
void cache_invalidate (cache_t * cache_ptr, const char * key)
Invalidates (removes) an entry from the cache index.
Removes a key from the cache. Decrements the entry's reference count.
Definition at line 530 of file cache.c.
Referenced by cache_get().
cache_load()
bool cache_load (cache_t * cache_ptr, const char * filename)
Loads cache entries from a binary file.
Entries that are already expired in the file are skipped. Entries loaded will be subject to the current cache's eviction policy (if the file contains more items than the cache capacity).
Parameters
cache_ptr The cache to load into.
filename The input file path.
Returns
true on success, false on I/O error or invalid format.
Definition at line 709 of file cache.c.
References cache_set().
cache_release()
void cache_release (const void * ptr)
Releases a reference to a zero-copy value.
Parameters
ptr The pointer returned by cache_get().
Releases a reference to a cached value. Must be called for every pointer returned by cache_get().
Definition at line 555 of file cache.c.
cache_save()
bool cache_save (cache_t * cache_ptr, const char * filename)
Serializes the current cache state to a binary file.
The operation locks shards one by one, allowing concurrent reads/writes to other shards while saving. The snapshot is not atomic across shards.
Parameters
cache_ptr The cache to save.
filename The output file path.
Returns
true on success, false on I/O error.
Definition at line 628 of file cache.c.
cache_set()
bool cache_set (cache_t * cache_ptr, const char * key, size_t klen, const void * value, size_t value_len, uint32_t ttl)
Stores a value in the cache.
Parameters
cache The cache handle.
key The key.
value The data to store.
value_len The length of the data.
ttl_override Optional TTL in seconds (0 uses default).
Returns
true on success, false on failure.
Inserts or updates a key-value pair in the cache.
If the cache is at capacity, triggers CLOCK eviction. Creates a new entry with the specified TTL.
Parameters
cache_ptr The cache instance
key The key string (null-terminated)
klen The length of the key.
value Pointer to value data
value_len Length of value data in bytes
ttl Time-to-live in seconds (0 = use default_ttl)
Returns
true on success, false on allocation failure
Definition at line 472 of file cache.c.
Referenced by cache_load().
get_total_cache_size()
size_t get_total_cache_size (cache_t * cache_ptr)
Returns the total number of entries currently in the cache across all shards. Thread-safe: acquires read locks on all shards.
Parameters
cache The cache instance.
Returns
Total number of cached entries, or 0 if cache is NULL.
Returns the total number of entries across all shards. Takes read locks on all shards.
Definition at line 586 of file cache.c.
get_total_capacity()
size_t get_total_capacity (cache_t * cache_ptr)
Returns the total capacity of the cache across all shards. Thread-safe: acquires read locks on all shards. Note: Capacity is set at creation and never changes, but we lock for consistency.
Parameters
cache The cache instance.
Returns
Total capacity, or 0 if cache is NULL.
Returns the total capacity across all shards. Takes read locks on all shards.
Definition at line 602 of file cache.c.