solidc: include/cstr.h File Reference
cstr.h File Reference
C string utilities and safe string operations.
#include "macros.h"
#include "str_utils.h"
#include <ctype.h>
#include <stdbool.h>
#include <stddef.h>
Typedefs
typedef struct cstr cstr
A dynamically resizable C-string with Small String Optimization (SSO).
Functions
cstr * cstr_init (size_t initial_capacity)
Creates a new empty cstr with specified initial capacity.
cstr * cstr_init_arena (Arena *arena, size_t initial_capacity)
Creates a new empty cstr using a custom arena allocator.
cstr * cstr_new (const char *input)
Creates a new cstr from a C string.
cstr * cstr_new_arena (Arena *arena, const char *input)
Creates a new cstr from a C string using a custom arena allocator.
void cstr_debug (const cstr *s)
Debug function to print comprehensive string information.
bool cstr_allocated (const cstr *s)
Checks if the string uses heap storage.
void cstr_free (cstr *s)
Frees a cstr and all associated memory.
size_t cstr_len (const cstr *s)
Returns the length of the string.
size_t cstr_capacity (const cstr *s)
Returns the current capacity of the string.
bool cstr_empty (const cstr *s)
Checks if the string is empty.
bool cstr_resize (cstr *s, size_t capacity)
Resizes the string's capacity.
bool cstr_append (cstr *s, const char *append)
Appends a C string to the cstr.
bool cstr_append_cstr (cstr *s, const cstr *append)
Appends a cstr to the cstr.
bool cstr_cat (cstr *dest, const cstr *src)
Alias for cstr_append_cstr (concatenation).
bool cstr_ncat (cstr *dest, const cstr *src, size_t n)
Appends at most n characters from src to dest.
bool cstr_copy (cstr *dest, const cstr *src)
Copies the content of src to dest (overwriting dest).
bool cstr_assign (cstr *dest, const cstr *src)
Alias for cstr_copy.
bool cstr_append_fast (cstr *s, const char *append)
Fast append assuming sufficient capacity.
PRINTF_FORMAT (1, 2) cstr *cstr_format(const char *format
Creates a new cstr from a formatted string (printf-style).
PRINTF_FORMAT (2, 3) bool cstr_append_fmt(cstr *s
Appends a formatted string to the cstr.
const char bool cstr_append_char (cstr *s, char c)
Appends a single character to the cstr.
bool cstr_prepend (cstr *s, const char *prepend)
Prepends a C string to the beginning of the cstr.
bool cstr_prepend_cstr (cstr *s, const cstr *prepend)
Prepends a cstr to the beginning of the cstr.
bool cstr_prepend_fast (cstr *s, const char *prepend)
Fast prepend assuming sufficient capacity.
bool cstr_insert (cstr *s, size_t index, const char *insert)
Inserts a C string at the specified position.
bool cstr_insert_cstr (cstr *s, size_t index, const cstr *insert)
Inserts a cstr at the specified position.
bool cstr_remove (cstr *s, size_t index, size_t count)
Removes a range of characters from the cstr.
void cstr_clear (cstr *s)
Clears the cstr, setting its length to 0.
size_t cstr_remove_all (cstr *s, const char *substr)
Removes all occurrences of a substring from the cstr.
size_t cstr_remove_all_cstr (cstr *s, const cstr *substr)
Removes all occurrences of a substring cstr from the cstr.
char cstr_at (const cstr *s, size_t index)
Returns the character at the specified index.
char * cstr_data (cstr *s)
Returns a mutable pointer to the cstr's data.
const char * cstr_data_const (const cstr *s)
Returns a const pointer to the cstr's data.
str_view cstr_as_view (const cstr *s)
Converts the cstr to a string view.
int cstr_compare (const cstr *s1, const cstr *s2)
Compares two cstrs lexicographically.
int cstr_cmp (const cstr *s1, const cstr *s2)
Alias for cstr_compare.
int cstr_ncmp (const cstr *s1, const cstr *s2, size_t n)
Compares two cstrs lexicographically with length limit.
bool cstr_equals (const cstr *s1, const cstr *s2)
Checks if two cstrs are equal.
bool cstr_starts_with (const cstr *s, const char *prefix)
Checks if the cstr starts with the given prefix.
bool cstr_starts_with_cstr (const cstr *s, const cstr *prefix)
Checks if the cstr starts with the given prefix cstr.
bool cstr_ends_with (const cstr *s, const char *suffix)
Checks if the cstr ends with the given suffix.
bool cstr_ends_with_cstr (const cstr *s, const cstr *suffix)
Checks if the cstr ends with the given suffix cstr.
int cstr_find (const cstr *s, const char *substr)
Finds the first occurrence of a substring in the cstr.
int cstr_find_cstr (const cstr *s, const cstr *substr)
Finds the first occurrence of a substring cstr in the cstr.
int cstr_rfind (const cstr *s, const char *substr)
Finds the last occurrence of a substring in the cstr.
int cstr_rfind_cstr (const cstr *s, const cstr *substr)
Finds the last occurrence of a substring cstr in the cstr.
bool cstr_contains (const cstr *s, const char *substr)
Checks if the cstr contains the given substring.
bool cstr_contains_cstr (const cstr *s, const cstr *substr)
Checks if the cstr contains the given substring cstr.
void cstr_lower (cstr *s)
Converts the cstr to lowercase in place.
void cstr_upper (cstr *s)
Converts the cstr to uppercase in place.
bool cstr_snakecase (cstr *s)
Converts the cstr to snake_case in place.
void cstr_camelcase (cstr *s)
Converts the cstr to camelCase in place.
void cstr_pascalcase (cstr *s)
Converts the cstr to PascalCase in place.
void cstr_titlecase (cstr *str)
Converts the cstr to Title Case in place.
void cstr_trim (cstr *s)
Removes leading and trailing whitespace from the cstr in place.
void cstr_rtrim (cstr *s)
Removes trailing whitespace from the cstr in place.
void cstr_ltrim (cstr *s)
Removes leading whitespace from the cstr in place.
void cstr_trim_chars (cstr *str, const char *chars)
Removes leading and trailing characters from the cstr in place based on a set of characters.
size_t cstr_count_substr (const cstr *str, const char *substr)
Count the number of occurrences of a substring within the string.
size_t cstr_count_substr_cstr (const cstr *str, const cstr *substr)
Count the number of occurrences of a substring cstr within the string.
void cstr_remove_substr (cstr *str, size_t start, size_t substr_length)
Remove characters in str from start index, up to start + length.
void cstr_remove_char (cstr *s, char c)
Removes all occurrences of a character from the cstr.
cstr * cstr_substr (const cstr *s, size_t start, size_t length)
Extracts a substring from the cstr.
cstr * cstr_replace (const cstr *s, const char *old, const char *new_str)
Replaces the first occurrence of a substring with another in the cstr.
cstr * cstr_replace_all (const cstr *s, const char *old, const char *new_str)
Replaces all occurrences of a substring with another.
cstr ** cstr_split (const cstr *s, const char *delim, size_t *count)
Splits the cstr into substrings based on a delimiter.
cstr * cstr_join (const cstr **strings, size_t count, const char *delim)
Joins multiple cstrs with a delimiter.
cstr * cstr_reverse (const cstr *s)
Creates a new cstr with the contents of the input cstr reversed.
void cstr_reverse_inplace (cstr *s)
Removes leading and trailing characters from the cstr in place based on a set of characters.
Detailed Description
C string utilities and safe string operations.
Definition in file cstr.h.
Typedef Documentation
cstr
typedef struct cstr cstr
A dynamically resizable C-string with Small String Optimization (SSO).
This structure implements an efficient string type that stores small strings (up to SSO_MAX_SIZE (24 bytes)) directly in the structure to avoid heap allocation, and larger strings on the heap. This provides optimal performance for both small and large strings while maintaining a consistent API.
The structure uses a union to overlay stack and heap storage modes:
Stack mode: For strings up to SSO_MAX_SIZE-1 characters
Heap mode: For larger strings, indicated by the MSB of capacity field
Note
All strings are null-terminated regardless of storage mode.
The structure size is optimized to fit common cache line sizes.
Definition at line 50 of file cstr.h.
Function Documentation
cstr_allocated()
bool cstr_allocated (const cstr * s)
Checks if the string uses heap storage.
Parameters
s Pointer to the cstr (can be NULL)
Returns
true if heap-allocated, false if stack-allocated or NULL
Definition at line 438 of file cstr.c.
References cstr_allocated().
Referenced by cstr_allocated().
cstr_append()
bool cstr_append (cstr * s, const char * append_str)
Appends a C string to the cstr.
Appends the entire source string to the end of the destination string, automatically reallocating if necessary.
Parameters
s Pointer to the destination cstr (must not be NULL)
append_str C string to append (must not be NULL)
Returns
true on success, false on allocation failure or invalid input
Definition at line 521 of file cstr.c.
References cstr_append().
Referenced by cstr_append().
cstr_append_char()
const char bool cstr_append_char (cstr * s, char c)
Appends a single character to the cstr.
Parameters
s Pointer to the destination cstr (must not be NULL)
c Character to append
Returns
true on success, false on allocation failure or invalid input
Definition at line 689 of file cstr.c.
References cstr_append_char().
Referenced by cstr_append_char().
cstr_append_cstr()
bool cstr_append_cstr (cstr * s, const cstr * append)
Appends a cstr to the cstr.
Appends the entire source cstr to the end of the destination cstr, automatically reallocating if necessary.
Parameters
s Pointer to the destination cstr (must not be NULL)
append_str cstr to append (must not be NULL)
Returns
true on success, false on allocation failure or invalid input
Definition at line 2025 of file cstr.c.
References cstr_append_cstr().
Referenced by cstr_append_cstr(), and cstr_cat().
cstr_append_fast()
bool cstr_append_fast (cstr * s, const char * append_str)
Fast append assuming sufficient capacity.
Appends a C string without checking or expanding capacity. The caller must ensure sufficient capacity exists.
Parameters
s Pointer to the destination cstr (must not be NULL)
append_str C string to append (must not be NULL)
Returns
true on success, false on invalid input
Precondition
Sufficient capacity must exist for the append operation
Definition at line 557 of file cstr.c.
References cstr_append_fast().
Referenced by cstr_append_fast().
cstr_as_view()
str_view cstr_as_view (const cstr * s)
Converts the cstr to a string view.
Creates a read-only view of the cstr's data and length.
Parameters
s Pointer to the cstr (can be NULL).
Returns
A str_view representing the cstr's data and length. If s is NULL, an empty str_view is returned.
Definition at line 946 of file cstr.c.
References cstr_as_view().
Referenced by cstr_as_view().
cstr_at()
char cstr_at (const cstr * s, size_t index)
Returns the character at the specified index.
Parameters
s Pointer to the cstr (can be NULL).
index Index of the character (0-based).
Returns
The character at the index, or '\0' if s is NULL or index is out of bounds.
Definition at line 908 of file cstr.c.
References cstr_at().
Referenced by cstr_at().
cstr_camelcase()
void cstr_camelcase (cstr * s)
Converts the cstr to camelCase in place.
Converts a string like "snake_case_string" or "PascalCaseString" to "camelCaseString". Removes underscores/spaces and capitalizes the following letter. The first character is converted to lowercase.
Parameters
s Pointer to the cstr (can be NULL).
Definition at line 1193 of file cstr.c.
References cstr_camelcase().
Referenced by cstr_camelcase().
cstr_capacity()
size_t cstr_capacity (const cstr * s)
Returns the current capacity of the string.
Parameters
s Pointer to the cstr (can be NULL)
Returns
Current capacity including null terminator, or 0 if s is NULL
Definition at line 484 of file cstr.c.
References cstr_capacity().
Referenced by cstr_capacity().
cstr_clear()
void cstr_clear (cstr * s)
Clears the cstr, setting its length to 0.
Sets the string's length to zero and null-terminates the first character. The capacity remains unchanged.
Parameters
s Pointer to the cstr (can be NULL).
Definition at line 853 of file cstr.c.
References cstr_clear().
Referenced by cstr_clear(), and cstr_trim_chars().
cstr_compare()
int cstr_compare (const cstr * s1, const cstr * s2)
Compares two cstrs lexicographically.
Compares the strings based on their character sequences.
Parameters
s1 First cstr (can be NULL).
s2 Second cstr (can be NULL).
Returns
Negative if s1 < s2, zero if s1 == s2, positive if s1 > s2. NULL strings are considered less than non-NULL strings. Two NULL strings are considered equal.
Definition at line 966 of file cstr.c.
References cstr_compare().
Referenced by cstr_cmp(), and cstr_compare().
cstr_contains()
bool cstr_contains (const cstr * s, const char * substr)
Checks if the cstr contains the given substring.
Parameters
s Pointer to the cstr (can be NULL).
substr Substring to find (can be NULL).
Returns
True if found, false otherwise.
Definition at line 2012 of file cstr.c.
References cstr_contains(), and cstr_find().
Referenced by cstr_contains().
cstr_contains_cstr()
bool cstr_contains_cstr (const cstr * s, const cstr * substr)
Checks if the cstr contains the given substring cstr.
Parameters
s Pointer to the cstr (can be NULL).
substr Substring to find (can be NULL).
Returns
True if found, false otherwise.
Definition at line 2014 of file cstr.c.
References cstr_contains_cstr(), and cstr_find_cstr().
Referenced by cstr_contains_cstr().
cstr_copy()
bool cstr_copy (cstr * dest, const cstr * src)
Copies the content of src to dest (overwriting dest).
Parameters
dest Destination cstr (must not be NULL).
src Source cstr (must not be NULL).
Returns
true on success.
Definition at line 2062 of file cstr.c.
References cstr_copy().
Referenced by cstr_assign(), and cstr_copy().
cstr_count_substr()
size_t cstr_count_substr (const cstr * str, const char * substr)
Count the number of occurrences of a substring within the string.
Parameters
str Pointer to the cstr (can be NULL).
substr Substring to count (can be NULL).
Returns
Number of occurrences. Returns 0 on invalid input or if substring is not found.
Definition at line 1477 of file cstr.c.
References cstr_count_substr().
Referenced by cstr_count_substr().
cstr_count_substr_cstr()
size_t cstr_count_substr_cstr (const cstr * str, const cstr * substr)
Count the number of occurrences of a substring cstr within the string.
Parameters
str Pointer to the cstr (can be NULL).
substr Substring to count (can be NULL).
Returns
Number of occurrences. Returns 0 on invalid input or if substring is not found.
Definition at line 2111 of file cstr.c.
References cstr_count_substr_cstr().
Referenced by cstr_count_substr_cstr().
cstr_data()
char * cstr_data (cstr * s)
Returns a mutable pointer to the cstr's data.
Provides direct access to the underlying character buffer. Use with caution, as modifying the buffer without updating the string's length can lead to inconsistencies.
Parameters
s Pointer to the cstr (can be NULL).
Returns
Pointer to the null-terminated string, or NULL if s is NULL.
Definition at line 925 of file cstr.c.
References cstr_data().
Referenced by cstr_data().
cstr_data_const()
const char * cstr_data_const (const cstr * s)
Returns a const pointer to the cstr's data.
Provides read-only access to the underlying character buffer.
Parameters
s Pointer to the cstr (can be NULL).
Returns
Const pointer to the null-terminated string, or NULL if s is NULL.
Definition at line 935 of file cstr.c.
References cstr_data_const().
Referenced by cstr_data_const().
cstr_debug()
void cstr_debug (const cstr * s)
Debug function to print comprehensive string information.
Outputs detailed information about the string's internal state, including storage mode, capacity, length, and raw data representation. Useful for debugging and understanding the SSO behavior.
Parameters
s Pointer to the cstr (can be NULL)
Definition at line 397 of file cstr.c.
References cstr_debug().
Referenced by cstr_debug().
cstr_empty()
bool cstr_empty (const cstr * s)
Checks if the string is empty.
Parameters
s Pointer to the cstr (can be NULL)
Returns
true if NULL or empty, false otherwise
Definition at line 492 of file cstr.c.
References cstr_empty().
Referenced by cstr_empty().
cstr_ends_with()
bool cstr_ends_with (const cstr * s, const char * suffix)
Checks if the cstr ends with the given suffix.
Parameters
s Pointer to the cstr (can be NULL).
suffix Suffix to check (can be NULL).
Returns
True if the cstr ends with the suffix, false otherwise. Returns false if s is NULL or suffix is NULL. An empty suffix is considered a suffix of any string.
Definition at line 1031 of file cstr.c.
References cstr_ends_with().
Referenced by cstr_ends_with().
cstr_ends_with_cstr()
bool cstr_ends_with_cstr (const cstr * s, const cstr * suffix)
Checks if the cstr ends with the given suffix cstr.
Parameters
s Pointer to the cstr (can be NULL).
suffix Suffix to check (can be NULL).
Returns
True if the cstr ends with the suffix, false otherwise.
Definition at line 1975 of file cstr.c.
References cstr_ends_with_cstr().
Referenced by cstr_ends_with_cstr().
cstr_equals()
bool cstr_equals (const cstr * s1, const cstr * s2)
Checks if two cstrs are equal.
Checks if the strings have the same length and the same character sequences.
Parameters
s1 First cstr (can be NULL).
s2 Second cstr (can be NULL).
Returns
True if the cstrs are equal, false otherwise. Two NULL strings are considered equal.
Definition at line 989 of file cstr.c.
References cstr_equals().
Referenced by cstr_equals().
cstr_find()
int cstr_find (const cstr * s, const char * substr)
Finds the first occurrence of a substring in the cstr.
Parameters
s Pointer to the cstr (can be NULL).
substr Substring to find (can be NULL).
Returns
Index of the first occurrence (0-based), or STR_NPOS (-1) if not found or invalid input.
Definition at line 1049 of file cstr.c.
References cstr_find().
Referenced by cstr_contains(), and cstr_find().
cstr_find_cstr()
int cstr_find_cstr (const cstr * s, const cstr * substr)
Finds the first occurrence of a substring cstr in the cstr.
Parameters
s Pointer to the cstr (can be NULL).
substr Substring to find (can be NULL).
Returns
Index of the first occurrence (0-based), or STR_NPOS (-1) if not found or invalid input.
Definition at line 1984 of file cstr.c.
References cstr_find_cstr().
Referenced by cstr_contains_cstr(), and cstr_find_cstr().
cstr_free()
void cstr_free (cstr * s)
Frees a cstr and all associated memory.
Releases all memory associated with the cstr, including heap-allocated string data if applicable. After calling this function, the pointer becomes invalid and must not be used.
Parameters
s Pointer to the cstr to free (can be NULL)
Note
Safe to call with NULL pointer
Definition at line 450 of file cstr.c.
References cstr_free().
Referenced by cstr_free(), cstr_replace_all(), and cstr_split().
cstr_init()
cstr * cstr_init (size_t initial_capacity)
Creates a new empty cstr with specified initial capacity.
Creates a new dynamically allocated cstr with at least the requested capacity. The string is initialized to empty but can grow up to the specified capacity without reallocation.
Parameters
initial_capacity Requested initial capacity including null terminator
Returns
Pointer to new cstr on success, NULL on allocation failure
Note
Caller must call str_free() to release memory
Actual capacity may be larger than requested for optimization
Definition at line 288 of file cstr.c.
References cstr_init(), and cstr_init_arena().
Referenced by cstr_init().
cstr_init_arena()
cstr * cstr_init_arena (Arena * arena, size_t initial_capacity)
Creates a new empty cstr using a custom arena allocator.
Parameters
arena The arena to allocate from.
initial_capacity Requested initial capacity.
Returns
Pointer to new cstr, or NULL on failure.
Definition at line 297 of file cstr.c.
References cstr_init_arena().
Referenced by cstr_init(), cstr_init_arena(), cstr_join(), cstr_new_arena(), cstr_replace(), cstr_replace_all(), cstr_reverse(), cstr_split(), and cstr_substr().
cstr_insert()
bool cstr_insert (cstr * s, size_t index, const char * insert_str)
Inserts a C string at the specified position.
Inserts the source string at the given index, shifting existing content to make room. Index must be within the current string length.
Parameters
s Pointer to the destination cstr (must not be NULL)
index Position to insert at (0-based, must be <= current length)
insert_str C string to insert (must not be NULL)
Returns
true on success, false on allocation failure or invalid input/index
Definition at line 784 of file cstr.c.
References cstr_insert().
Referenced by cstr_insert().
cstr_insert_cstr()
bool cstr_insert_cstr (cstr * s, size_t index, const cstr * insert)
Inserts a cstr at the specified position.
Inserts the source cstr at the given index, shifting existing content to make room. Index must be within the current string length.
Parameters
s Pointer to the destination cstr (must not be NULL)
index Position to insert at (0-based, must be <= current length)
insert_str cstr to insert (must not be NULL)
Returns
true on success, false on allocation failure or invalid input/index
Definition at line 2093 of file cstr.c.
References cstr_insert_cstr().
Referenced by cstr_insert_cstr().
cstr_join()
cstr * cstr_join (const cstr ** strings, size_t count, const char * delim)
Joins multiple cstrs with a delimiter.
Concatenates an array of cstrs into a single new cstr, separated by the specified delimiter.
Parameters
strings Array of cstr pointers (can be NULL or empty). Each cstr pointer must not be NULL.
count Number of cstrs in the array.
delim Delimiter string (can be NULL for no delimiter).
Returns
Pointer to the new cstr with joined strings, or NULL on invalid input or allocation failure. Returns a new empty cstr if the input array is empty.
Definition at line 1850 of file cstr.c.
References cstr_init_arena(), cstr_join(), and cstr_new().
Referenced by cstr_join().
cstr_len()
size_t cstr_len (const cstr * s)
Returns the length of the string.
Parameters
s Pointer to the cstr (can be NULL)
Returns
Length excluding null terminator, or 0 if s is NULL
Definition at line 476 of file cstr.c.
References cstr_len().
Referenced by cstr_len().
cstr_lower()
void cstr_lower (cstr * s)
Converts the cstr to lowercase in place.
Converts all uppercase characters in the string to their lowercase equivalents.
Parameters
s Pointer to the cstr (can be NULL).
Definition at line 1101 of file cstr.c.
References cstr_lower().
Referenced by cstr_lower().
cstr_ltrim()
void cstr_ltrim (cstr * s)
Removes leading whitespace from the cstr in place.
Removes whitespace characters (as defined by isspace()) from the beginning of the string.
Parameters
s Pointer to the cstr (can be NULL).
Definition at line 1392 of file cstr.c.
References cstr_ltrim().
Referenced by cstr_ltrim().
cstr_ncmp()
int cstr_ncmp (const cstr * s1, const cstr * s2, size_t n)
Compares two cstrs lexicographically with length limit.
Parameters
s1 First cstr (can be NULL).
s2 Second cstr (can be NULL).
n Maximum number of characters to compare.
Returns
Negative if s1 < s2, zero if s1 == s2, positive if s1 > s2.
Definition at line 2154 of file cstr.c.
References cstr_ncmp().
Referenced by cstr_ncmp().
cstr_new()
cstr * cstr_new (const char * input)
Creates a new cstr from a C string.
Creates a new cstr containing a copy of the input C string. The new string will have exactly the capacity needed to store the input plus room for growth.
Parameters
input C string to copy (must be null-terminated, can be NULL)
Returns
Pointer to new cstr on success, NULL on allocation failure or if input is NULL
Note
Caller must call str_free() to release memory
Definition at line 358 of file cstr.c.
References cstr_new(), and cstr_new_arena().
Referenced by cstr_join(), and cstr_new().
cstr_new_arena()
cstr * cstr_new_arena (Arena * arena, const char * input)
Creates a new cstr from a C string using a custom arena allocator.
Parameters
arena The arena to allocate from.
input C string to copy.
Returns
Pointer to new cstr, or NULL on failure.
Definition at line 367 of file cstr.c.
References cstr_init_arena(), and cstr_new_arena().
Referenced by cstr_new(), cstr_new_arena(), cstr_replace(), cstr_replace_all(), cstr_reverse(), cstr_split(), and cstr_substr().
cstr_pascalcase()
void cstr_pascalcase (cstr * s)
Converts the cstr to PascalCase in place.
Converts a string like "snake_case_string" or "camelCaseString" to "PascalCaseString". Removes underscores/spaces and capitalizes the following letter. The first character is converted to uppercase.
Parameters
s Pointer to the cstr (can be NULL).
Definition at line 1243 of file cstr.c.
References cstr_pascalcase().
Referenced by cstr_pascalcase().
cstr_prepend()
bool cstr_prepend (cstr * s, const char * prepend_str)
Prepends a C string to the beginning of the cstr.
Inserts the source string at the beginning of the destination string, shifting existing content to the right.
Parameters
s Pointer to the destination cstr (must not be NULL)
prepend_str C string to prepend (must not be NULL)
Returns
true on success, false on allocation failure or invalid input
Definition at line 717 of file cstr.c.
References cstr_prepend().
Referenced by cstr_prepend().
cstr_prepend_cstr()
bool cstr_prepend_cstr (cstr * s, const cstr * prepend)
Prepends a cstr to the beginning of the cstr.
Inserts the source cstr at the beginning of the destination cstr, shifting existing content to the right.
Parameters
s Pointer to the destination cstr (must not be NULL)
prepend_str cstr to prepend (must not be NULL)
Returns
true on success, false on allocation failure or invalid input
Definition at line 2076 of file cstr.c.
References cstr_prepend_cstr().
Referenced by cstr_prepend_cstr().
cstr_prepend_fast()
bool cstr_prepend_fast (cstr * s, const char * prepend_str)
Fast prepend assuming sufficient capacity.
Prepends a C string without checking or expanding capacity. The caller must ensure sufficient capacity exists.
Parameters
s Pointer to the destination cstr (must not be NULL)
prepend_str C string to prepend (must not be NULL)
Returns
true on success, false on invalid input
Precondition
Sufficient capacity must exist for the prepend operation
Definition at line 750 of file cstr.c.
References cstr_prepend_fast().
Referenced by cstr_prepend_fast().
cstr_remove()
bool cstr_remove (cstr * s, size_t index, size_t count)
Removes a range of characters from the cstr.
Removes 'count' characters starting from 'index'. If 'index' + 'count' extends beyond the string's length, characters are removed until the end.
Parameters
s Pointer to the cstr (must not be NULL)
index Starting index of the range to remove.
count Number of characters to remove.
Returns
True on success, false on invalid input or index.
Definition at line 819 of file cstr.c.
References cstr_remove().
Referenced by cstr_remove().
cstr_remove_all()
size_t cstr_remove_all (cstr * s, const char * substr)
Removes all occurrences of a substring from the cstr.
Removes all instances of the specified substring from the string.
Parameters
s Pointer to the cstr (must not be NULL).
substr Substring to remove (must not be NULL and not empty).
Returns
Number of occurrences removed. Returns 0 on invalid input or if substring is not found.
Definition at line 870 of file cstr.c.
References cstr_remove_all().
Referenced by cstr_remove_all().
cstr_remove_all_cstr()
size_t cstr_remove_all_cstr (cstr * s, const cstr * substr)
Removes all occurrences of a substring cstr from the cstr.
Removes all instances of the specified substring cstr from the string.
Parameters
s Pointer to the cstr (must not be NULL).
substr Substring to remove (must not be NULL and not empty).
Returns
Number of occurrences removed. Returns 0 on invalid input or if substring is not found.
Definition at line 2127 of file cstr.c.
References cstr_remove_all_cstr().
Referenced by cstr_remove_all_cstr().
cstr_remove_char()
void cstr_remove_char (cstr * s, char c)
Removes all occurrences of a character from the cstr.
Removes all instances of the specified character from the string.
Parameters
s Pointer to the cstr (must not be NULL).
c Character to remove.
Definition at line 1530 of file cstr.c.
References cstr_remove_char().
Referenced by cstr_remove_char().
cstr_remove_substr()
void cstr_remove_substr (cstr * str, size_t start, size_t substr_length)
Remove characters in str from start index, up to start + length.
Parameters
str Pointer to cstr.
start Start index of substring in str.
substr_length Length of the substring.
Definition at line 1496 of file cstr.c.
References cstr_remove_substr().
Referenced by cstr_remove_substr().
cstr_replace()
cstr * cstr_replace (const cstr * s, const char * old_str, const char * new_str)
Replaces the first occurrence of a substring with another in the cstr.
Creates a new cstr where the first occurrence of 'old_str' is replaced by 'new_str'.
Parameters
s Pointer to the cstr (can be NULL).
old_str Substring to replace (can be NULL). Cannot be empty.
new_str Replacement substring (can be NULL).
Returns
Pointer to the new cstr with the first occurrence replaced, or NULL on invalid input or allocation failure.
Definition at line 1598 of file cstr.c.
References cstr_init_arena(), cstr_new_arena(), and cstr_replace().
Referenced by cstr_replace().
cstr_replace_all()
cstr * cstr_replace_all (const cstr * s, const char * old_sub, const char * new_sub)
Replaces all occurrences of a substring with another.
Creates a new cstr where all non-overlapping occurrences of 'old_sub' are replaced by 'new_sub'.
Parameters
s Pointer to the cstr (can be NULL).
old_sub Substring to replace (can be NULL). Cannot be empty.
new_sub Replacement substring (can be NULL).
Returns
Pointer to the new cstr with replacements, or NULL on invalid input or allocation failure.
Definition at line 1662 of file cstr.c.
References cstr_free(), cstr_init_arena(), cstr_new_arena(), and cstr_replace_all().
Referenced by cstr_replace_all().
cstr_resize()
bool cstr_resize (cstr * s, size_t new_capacity)
Resizes the string's capacity.
Ensures the string has at least the specified capacity. If the current capacity is already sufficient, no operation is performed.
Parameters
s Pointer to the cstr (must not be NULL)
new_capacity Minimum required capacity including null terminator
Returns
true on success, false on allocation failure or if s is NULL
Definition at line 504 of file cstr.c.
References cstr_resize().
Referenced by cstr_resize().
cstr_reverse()
cstr * cstr_reverse (const cstr * s)
Creates a new cstr with the contents of the input cstr reversed.
Parameters
s Pointer to the cstr (can be NULL).
Returns
Pointer to the new reversed cstr, or NULL on invalid input or allocation failure.
Definition at line 1922 of file cstr.c.
References cstr_init_arena(), cstr_new_arena(), and cstr_reverse().
Referenced by cstr_reverse().
cstr_reverse_inplace()
void cstr_reverse_inplace (cstr * s)
Removes leading and trailing characters from the cstr in place based on a set of characters.
Removes characters specified in the 'chars' string from both the beginning and the end of the string.
Parameters
s Pointer to the cstr (can be NULL).
chars C string containing characters to remove (can be NULL or empty).
Removes leading and trailing characters from the cstr in place based on a set of characters.
Reverses the string data within the existing cstr buffer.
Parameters
s Pointer to the cstr (can be NULL).
Definition at line 1955 of file cstr.c.
References cstr_reverse_inplace().
Referenced by cstr_reverse_inplace().
cstr_rfind()
int cstr_rfind (const cstr * s, const char * substr)
Finds the last occurrence of a substring in the cstr.
Parameters
s Pointer to the cstr (can be NULL).
substr Substring to find (can be NULL).
Returns
Index of the last occurrence (0-based), or STR_NPOS (-1) if not found or invalid input.
Definition at line 1065 of file cstr.c.
References cstr_rfind().
Referenced by cstr_rfind().
cstr_rfind_cstr()
int cstr_rfind_cstr (const cstr * s, const cstr * substr)
Finds the last occurrence of a substring cstr in the cstr.
Parameters
s Pointer to the cstr (can be NULL).
substr Substring to find (can be NULL).
Returns
Index of the last occurrence (0-based), or STR_NPOS (-1) if not found or invalid input.
Definition at line 1993 of file cstr.c.
References cstr_rfind_cstr().
Referenced by cstr_rfind_cstr().
cstr_rtrim()
void cstr_rtrim (cstr * s)
Removes trailing whitespace from the cstr in place.
Removes whitespace characters (as defined by isspace()) from the end of the string.
Parameters
s Pointer to the cstr (can be NULL).
Definition at line 1360 of file cstr.c.
References cstr_rtrim().
Referenced by cstr_rtrim().
cstr_snakecase()
bool cstr_snakecase (cstr * s)
Converts the cstr to snake_case in place.
Converts a string like "CamelCaseString" or "PascalCaseString" to "camel_case_string". Inserts underscores before uppercase letters (except the first) and converts all characters to lowercase.
Parameters
s Pointer to the cstr (can be NULL).
Returns
true on success, false on allocation failure or invalid input.
Definition at line 1138 of file cstr.c.
References cstr_snakecase().
Referenced by cstr_snakecase().
cstr_split()
cstr ** cstr_split (const cstr * s, const char * delim, size_t * count_out)
Splits the cstr into substrings based on a delimiter.
Divides the string into an array of new cstr objects, using the delimiter as the separator. Consecutive delimiters result in empty strings in the output array.
Parameters
s Pointer to the cstr (can be NULL).
delim Delimiter string (can be NULL). If empty, returns an array containing a copy of the original string.
count_out Pointer to store the number of resulting substrings (must not be NULL).
Returns
Array of cstr pointers, or NULL on invalid input or allocation failure. The caller is responsible for freeing the array and each cstr within it.
Definition at line 1756 of file cstr.c.
References cstr_free(), cstr_init_arena(), cstr_new_arena(), and cstr_split().
Referenced by cstr_split().
cstr_starts_with()
bool cstr_starts_with (const cstr * s, const char * prefix)
Checks if the cstr starts with the given prefix.
Parameters
s Pointer to the cstr (can be NULL).
prefix Prefix to check (can be NULL).
Returns
True if the cstr starts with the prefix, false otherwise. Returns false if s is NULL or prefix is NULL. An empty prefix is considered a prefix of any string.
Definition at line 1013 of file cstr.c.
References cstr_starts_with().
Referenced by cstr_starts_with().
cstr_starts_with_cstr()
bool cstr_starts_with_cstr (const cstr * s, const cstr * prefix)
Checks if the cstr starts with the given prefix cstr.
Parameters
s Pointer to the cstr (can be NULL).
prefix Prefix to check (can be NULL).
Returns
True if the cstr starts with the prefix, false otherwise.
Definition at line 2016 of file cstr.c.
References cstr_starts_with_cstr().
Referenced by cstr_starts_with_cstr().
cstr_substr()
cstr * cstr_substr (const cstr * s, size_t start, size_t length)
Extracts a substring from the cstr.
Creates a new cstr containing a portion of the original string starting at 'start' index with the specified 'length'. If 'start' is out of bounds or 'start' + 'length' exceeds the original string's length, the substring will be truncated accordingly.
Parameters
s Pointer to the cstr (can be NULL).
start Starting index of the substring (0-based).
length Length of the substring.
Returns
Pointer to the new cstr containing the substring, or NULL on invalid input or allocation failure.
Definition at line 1563 of file cstr.c.
References cstr_init_arena(), cstr_new_arena(), and cstr_substr().
Referenced by cstr_substr().
cstr_titlecase()
void cstr_titlecase (cstr * s)
Converts the cstr to Title Case in place.
Capitalizes the first character of each word and converts the rest to lowercase. Words are delimited by spaces.
Parameters
s Pointer to the cstr (can be NULL).
Definition at line 1289 of file cstr.c.
References cstr_titlecase().
Referenced by cstr_titlecase().
cstr_trim()
void cstr_trim (cstr * s)
Removes leading and trailing whitespace from the cstr in place.
Removes whitespace characters (as defined by isspace()) from both the beginning and the end of the string.
Parameters
s Pointer to the cstr (can be NULL).
Definition at line 1320 of file cstr.c.
References cstr_trim().
Referenced by cstr_trim().
cstr_trim_chars()
void cstr_trim_chars (cstr * s, const char * chars)
Removes leading and trailing characters from the cstr in place based on a set of characters.
Removes characters specified in the 'chars' string from both the beginning and the end of the string.
Parameters
s Pointer to the cstr (can be NULL).
chars C string containing characters to remove (can be NULL or empty).
Definition at line 1431 of file cstr.c.
References cstr_clear(), and cstr_trim_chars().
Referenced by cstr_trim_chars().
cstr_upper()
void cstr_upper (cstr * s)
Converts the cstr to uppercase in place.
Converts all lowercase characters in the string to their uppercase equivalents.
Parameters
s Pointer to the cstr (can be NULL).
Definition at line 1119 of file cstr.c.
References cstr_upper().
Referenced by cstr_upper().
PRINTF_FORMAT() [1/2]
PRINTF_FORMAT (1 , 2) const
Creates a new cstr from a formatted string (printf-style).
Creates a new cstr by formatting the input according to the format string, similar to sprintf but with automatic memory management.
Parameters
format Printf-style format string (must not be NULL)
... Arguments for the format string
Returns
Pointer to new formatted cstr on success, NULL on failure
Note
Caller must call str_free() to release memory
PRINTF_FORMAT() [2/2]
PRINTF_FORMAT (2 , 3)
Appends a formatted string to the cstr.
Appends text formatted according to printf-style format string and arguments to the end of the existing string content.
Parameters
s Pointer to the destination cstr (must not be NULL)
format Printf-style format string (must not be NULL)
... Arguments for the format string
Returns
true on success, false on allocation failure or formatting error