solidc: src/flags.c File Reference
flags.c File Reference
Command-line flag parsing library implementation.
#include "../include/flags.h"
#include "../include/str_utils.h"
Functions
FlagParser * flag_parser_new (const char *name, const char *description)
Create a new flag parser.
void flag_parser_free (FlagParser *fp)
Free a flag parser and all associated resources.
void flag_parser_set_footer (FlagParser *parser, const char *footer)
Set optional footer text for help output.
void flag_set_pre_invoke (FlagParser *fp, void(*pre_invoke)(void *user_data))
Set pre-invocation callback for a parser.
Flag * flag_add (FlagParser *fp, FlagDataType type, const char *name, char short_name, const char *desc, void *value_ptr, bool required)
FlagParser * flag_add_subcommand (FlagParser *fp, const char *name, const char *desc, void(*handler)(void *data))
bool flag_invoke_subcommand (FlagParser *fp, void(*pre_invoke)(void *user_data), void *user_data)
Invoke the active subcommand with optional pre-invoke callback.
void flag_set_validator (Flag *flag, FlagValidator validator)
FlagStatus flag_parse (FlagParser *fp, int argc, char **argv)
Parse command-line arguments.
FlagStatus flag_parse_and_invoke (FlagParser *fp, int argc, char **argv, void *user_data)
void flag_print_usage (FlagParser *fp)
Print usage/help information for the parser.
const char * flag_get_error (FlagParser *fp)
Get the last error message.
int flag_positional_count (FlagParser *fp)
Get count of positional arguments.
const char * flag_positional_at (FlagParser *fp, int i)
bool flag_is_present (FlagParser *fp, const char *name)
const char * flag_status_str (FlagStatus s)
Convert FlagStatus code to string.
Detailed Description
Command-line flag parsing library implementation.
This library provides a flexible command-line argument parser with support for:
Multiple data types (bool, integers, floats, strings, etc.)
Long flags (–flag) and short flags (-f)
Subcommands with nested parsing
Custom validators
Automatic help generation
Default value display
Positional arguments
Definition in file flags.c.
Function Documentation
flag_add()
Flag * flag_add (FlagParser * parser, FlagDataType type, const char * name, char short_name, const char * desc, void * value_ptr, bool required)
Core function to register a flag. Use the macros (flag_int, flag_bool) instead of calling this directly.
Definition at line 373 of file flags.c.
flag_add_subcommand()
FlagParser * flag_add_subcommand (FlagParser * parser, const char * name, const char * desc, void(*)(void *data) handler)
Register a subcommand. Returns the child parser.
Definition at line 417 of file flags.c.
References flag_parser_new().
flag_get_error()
const char * flag_get_error (FlagParser * fp)
Get the last error message.
Parameters
fp Parser to get error from
Returns
Error string, or empty string if no error
Returns the error message from the most recently failed parse operation. If a subcommand is active, returns that subcommand's error instead.
Definition at line 1039 of file flags.c.
flag_invoke_subcommand()
bool flag_invoke_subcommand (FlagParser * fp, void(*)(void *user_data) pre_invoke, void * user_data)
Invoke the active subcommand with optional pre-invoke callback.
Parameters
fp Parser with active subcommand
pre_invoke Optional callback to run before handler
user_data User data passed to callbacks
Returns
true if subcommand was invoked, false if no active subcommand
This is typically used for manual invocation. For automatic invocation after parsing, use flag_parse_and_invoke() instead.
Definition at line 443 of file flags.c.
flag_is_present()
bool flag_is_present (FlagParser * parser, const char * flag_name)
Check if a flag was explicitly provided.
Definition at line 1093 of file flags.c.
flag_parse()
FlagStatus flag_parse (FlagParser * fp, int argc, char ** argv)
Parse command-line arguments.
Parameters
fp Parser to use
argc Argument count (from main)
argv Argument vector (from main)
Returns
FLAG_OK on success, error code otherwise
Parses argv according to registered flags and subcommands. Supports:
Long flags: –flag=value or –flag value
Short flags: -f value or -fvalue
Boolean flags: –flag (no value needed)
Flag combinations: -abc (multiple boolean flags)
End of options: – (remaining args are positional)
Automatic –help handling
After successful parsing, use flag_get_error() to retrieve error messages, flag_positional_at() to access positional args, and flag_is_present() to check if optional flags were provided.
Definition at line 675 of file flags.c.
References flag_parse(), and flag_print_usage().
Referenced by flag_parse(), and flag_parse_and_invoke().
flag_parse_and_invoke()
FlagStatus flag_parse_and_invoke (FlagParser * parser, int argc, char ** argv, void * user_data)
Parse arguments and automatically invoke subcommand if present.
Parameters
parser The parser instance.
argc Argument count.
argv Argument vector.
user_data Optional user data passed to pre-invoke and handler callbacks.
Returns
FLAG_OK on success.
Definition at line 864 of file flags.c.
References flag_parse().
flag_parser_free()
void flag_parser_free (FlagParser * fp)
Free a flag parser and all associated resources.
Parameters
fp Parser to free
Recursively frees all subcommands and their flags. Safe to call with NULL.
Definition at line 302 of file flags.c.
References flag_parser_free().
Referenced by flag_parser_free().
flag_parser_new()
FlagParser * flag_parser_new (const char * name, const char * description)
Create a new flag parser.
Parameters
name Name of the program or command
description Description shown in help text
Returns
Newly allocated FlagParser, or NULL on failure
The returned parser must be freed with flag_parser_free() when done.
Definition at line 288 of file flags.c.
Referenced by flag_add_subcommand().
flag_parser_set_footer()
void flag_parser_set_footer (FlagParser * parser, const char * footer)
Set optional footer text for help output.
Parameters
parser Parser to configure
footer Footer text (will be copied)
Definition at line 330 of file flags.c.
flag_positional_at()
const char * flag_positional_at (FlagParser * parser, int index)
Get positional argument at index.
Definition at line 1074 of file flags.c.
flag_positional_count()
int flag_positional_count (FlagParser * fp)
Get count of positional arguments.
Parameters
fp Parser to query
Returns
Number of positional arguments
Definition at line 1057 of file flags.c.
flag_print_usage()
void flag_print_usage (FlagParser * fp)
Print usage/help information for the parser.
Parameters
fp Parser to print usage for
Prints formatted help text including:
Usage line
Description
All flags with types, descriptions, and default values
Required flag markers
Subcommands (if any)
Footer text (if set)
If an active subcommand exists, prints help for that subcommand instead.
Definition at line 1017 of file flags.c.
Referenced by flag_parse().
flag_set_pre_invoke()
void flag_set_pre_invoke (FlagParser * fp, void(*)(void *user_data) pre_invoke)
Set pre-invocation callback for a parser.
Parameters
fp Parser to configure
pre_invoke Function to call before command handler
The pre_invoke callback is called before the command handler, useful for global setup or initialization.
Definition at line 344 of file flags.c.
flag_set_validator()
void flag_set_validator (Flag * flag, FlagValidator validator)
Attach a custom validator to a specific flag.
Definition at line 484 of file flags.c.
flag_status_str()
const char * flag_status_str (FlagStatus s)
Convert FlagStatus code to string.
Parameters
s Status code
Returns
Human-readable status string
Definition at line 1103 of file flags.c.