solidc: include/pipeline.h File Reference
pipeline.h File Reference
Data pipeline utilities for processing streams.
#include <fcntl.h>
#include <sys/wait.h>
#include <unistd.h>
Classes
struct CommandNode
Structure representing a command in a pipeline.
Typedefs
typedef struct CommandNode CommandNode
Structure representing a command in a pipeline.
Functions
CommandNode * create_command_node (char **args)
Create a new CommandNode.
void execute_pipeline (CommandNode *head, int output_fd)
Execute a pipeline of commands.
void free_pipeline (CommandNode *head)
Free the linked list of commands.
void build_pipeline (CommandNode **commands)
Build the pipeline using a NULL-terminated array of CommandNode pointers.
Detailed Description
Data pipeline utilities for processing streams.
Definition in file pipeline.h.
Function Documentation
build_pipeline()
void build_pipeline (CommandNode ** commands)
Build the pipeline using a NULL-terminated array of CommandNode pointers.
Parameters
commands Array of CommandNode pointers, terminated by NULL.
Definition at line 250 of file pipeline.c.
References build_pipeline().
Referenced by build_pipeline().
create_command_node()
CommandNode * create_command_node (char ** args)
Create a new CommandNode.
Parameters
args Array of command arguments (NULL-terminated).
Returns
Pointer to the newly created CommandNode.
Definition at line 19 of file pipeline.c.
References create_command_node().
Referenced by create_command_node().
execute_pipeline()
void execute_pipeline (CommandNode * head, int output_fd)
Execute a pipeline of commands.
Parameters
head Pointer to the first CommandNode in the pipeline.
output_fd Optional file descriptor to capture the output of the last command. If -1, the output is not redirected.
Execute a pipeline of commands.
Parameters
head Pointer to the first CommandNode in the pipeline.
output_fd Optional file descriptor to capture the output of the last command. If -1, the output is not redirected.
Definition at line 165 of file pipeline.c.
References execute_pipeline().
Referenced by execute_pipeline().
free_pipeline()
void free_pipeline (CommandNode * head)
Free the linked list of commands.
Parameters
head Pointer to the first CommandNode in the pipeline.
Definition at line 235 of file pipeline.c.
References free_pipeline().
Referenced by free_pipeline().