solidc: include/process.h File Reference
process.h File Reference
A modern, cross-platform API for process management and IPC.
#include "env.h"
#include <assert.h>
#include <stdbool.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>
#include <fcntl.h>
#include <signal.h>
#include <sys/select.h>
#include <sys/types.h>
#include <sys/wait.h>
#include <unistd.h>
Classes
struct ProcessOptions
Options for process creation.
struct ProcessResult
Result information after a process completes.
Typedefs
typedef struct ProcessHandle ProcessHandle
Process handle type (platform-specific details hidden in implementation)
typedef struct PipeHandle PipeHandle
Pipe handle type for IPC (platform-specific details hidden in implementation)
typedef struct FileRedirection FileRedirection
Enumerations
enum ProcessError
Error codes for process operations.
enum ProcessStream
Standard IO stream types for redirection.
Functions
ProcessError process_create (ProcessHandle **handle, const char *command, const char *const argv[], const ProcessOptions *options)
Create a new process When custom environment is provided, command must be an absolute path or relative path (containing '/'), as execve() does not search PATH.
ProcessError process_wait (ProcessHandle *handle, ProcessResult *result, int timeout_ms)
Wait for a process to complete.
ProcessError process_terminate (ProcessHandle *handle, bool force)
Terminate a running process.
void process_free (ProcessHandle *handle)
Free resources associated with a process handle.
bool pipe_read_closed (PipeHandle *handle)
bool pipe_write_closed (PipeHandle *handle)
PipeFd pipe_read_fd (PipeHandle *handle)
PipeFd pipe_write_fd (PipeHandle *handle)
ProcessError pipe_create (PipeHandle **pipe)
Create a new pipe for IPC.
ProcessError pipe_set_nonblocking (PipeHandle *pipe, bool nonblocking)
Set non-blocking mode on a pipe.
ProcessError pipe_read (PipeHandle *pipe, void *buffer, size_t size, size_t *bytes_read, int timeout_ms)
Read data from a pipe.
ProcessError pipe_write (PipeHandle *pipe, const void *buffer, size_t size, size_t *bytes_written, int timeout_ms)
Write data to a pipe.
void pipe_close (PipeHandle *pipe)
Close a pipe.
const char * process_error_string (ProcessError error)
Get a string description of a process error.
ProcessError process_run_and_capture (const char *command, const char *const argv[], ProcessOptions *options, int *exit_code)
Run a command and capture its output.
ProcessError process_redirect_to_file (FileRedirection **redirection, const char *filepath, int flags, unsigned int mode)
Create a new file redirection for a process.
ProcessError process_redirect_to_fd (FileRedirection **redirection, int fd, bool close_on_exec)
Create a file redirection from an existing file descriptor.
void process_close_redirection (FileRedirection *redirection)
Close and free a file redirection.
ProcessError process_run_with_multiwriter (ProcessResult *result, const char *cmd, const char *args[], int output_fds[], int error_fds[])
Run the command in a process that duplicates output to multiple destinations.
ProcessError process_create_with_redirection (ProcessHandle **handle, const char *command, const char *const argv[], const ExtProcessOptions *options)
Create a process with extended redirection options.
ProcessError process_run_with_file_redirection (ProcessHandle **handle, const char *command, const char *const argv[], const char *stdout_file, const char *stderr_file, bool append)
Create a process that redirects its output from stdout and/or stderr to files.
Detailed Description
A modern, cross-platform API for process management and IPC.
Definition in file process.h.
Typedef Documentation
FileRedirection
typedef struct FileRedirection FileRedirection
File redirection handle
Definition at line 88 of file process.h.
Function Documentation
pipe_close()
void pipe_close (PipeHandle * pipe)
Close a pipe.
Parameters
[in] pipe Pipe handle to close
Definition at line 547 of file process.c.
pipe_create()
ProcessError pipe_create (PipeHandle ** pipe)
Create a new pipe for IPC.
Parameters
[out] pipe Pointer to receive the pipe handle
Returns
PROCESS_SUCCESS on success, error code otherwise
Definition at line 240 of file process.c.
pipe_read()
ProcessError pipe_read (PipeHandle * pipe, void * buffer, size_t size, size_t * bytes_read, int timeout_ms)
Read data from a pipe.
Parameters
[in] pipe Pipe handle
[out] buffer Buffer to receive the data
[in] size Buffer size
[out] bytes_read Pointer to receive the number of bytes read (can be NULL)
[in] timeout_ms Timeout in milliseconds (-1 = wait indefinitely)
Returns
PROCESS_SUCCESS on success, error code otherwise
Definition at line 335 of file process.c.
pipe_read_closed()
bool pipe_read_closed (PipeHandle * handle)
Returns True if pipe read closed.
Definition at line 184 of file process.c.
pipe_read_fd()
PipeFd pipe_read_fd (PipeHandle * handle)
Returns the pipe write read descriptor.
Definition at line 194 of file process.c.
pipe_set_nonblocking()
ProcessError pipe_set_nonblocking (PipeHandle * pipe, bool nonblocking)
Set non-blocking mode on a pipe.
Parameters
pipe Pipe handle
nonblocking true to enable non-blocking mode, false for blocking
Returns
ProcessError
Definition at line 283 of file process.c.
pipe_write()
ProcessError pipe_write (PipeHandle * pipe, const void * buffer, size_t size, size_t * bytes_written, int timeout_ms)
Write data to a pipe.
Parameters
[in] pipe Pipe handle
[in] buffer Data to write
[in] size Number of bytes to write
[out] bytes_written Pointer to receive the number of bytes written (can be NULL)
[in] timeout_ms Timeout in milliseconds (-1 = wait indefinitely)
Returns
PROCESS_SUCCESS on success, error code otherwise
Definition at line 445 of file process.c.
pipe_write_closed()
bool pipe_write_closed (PipeHandle * handle)
Returns True if pipe write closed.
Definition at line 189 of file process.c.
pipe_write_fd()
PipeFd pipe_write_fd (PipeHandle * handle)
Returns the pipe write file descriptor.
Definition at line 199 of file process.c.
process_close_redirection()
void process_close_redirection (FileRedirection * redirection)
Close and free a file redirection.
Parameters
redirection The redirection to close
Definition at line 1088 of file process.c.
Referenced by process_run_with_file_redirection().
process_create()
ProcessError process_create (ProcessHandle ** handle, const char * command, const char *const argv[], const ProcessOptions * options)
Create a new process When custom environment is provided, command must be an absolute path or relative path (containing '/'), as execve() does not search PATH.
Parameters
[out] handle Pointer to receive the process handle
[in] command Path to executable
[in] argv NULL-terminated array of arguments (argv[0] should be command name)
[in] options Process creation options (NULL for defaults)
Returns
PROCESS_SUCCESS on success, error code otherwise
Definition at line 814 of file process.c.
Referenced by process_run_and_capture().
process_create_with_redirection()
ProcessError process_create_with_redirection (ProcessHandle ** handle, const char * command, const char *const argv[], const ExtProcessOptions * options)
Create a process with extended redirection options.
Parameters
[out] handle Pointer to store the process handle
[in] command Command to execute
[in] argv Arguments for the command (NULL-terminated)
[in] options Process options with extended IO
Returns
ProcessError
Definition at line 1110 of file process.c.
Referenced by process_run_with_file_redirection().
process_error_string()
const char * process_error_string (ProcessError error)
Get a string description of a process error.
Parameters
[in] error Error code
Returns
Human-readable error description
Definition at line 202 of file process.c.
process_free()
void process_free (ProcessHandle * handle)
Free resources associated with a process handle.
Parameters
[in] handle Process handle to free
Definition at line 840 of file process.c.
Referenced by process_run_and_capture().
process_redirect_to_fd()
ProcessError process_redirect_to_fd (FileRedirection ** redirection, int fd, bool close_on_exec)
Create a file redirection from an existing file descriptor.
Parameters
[out] redirection Pointer to store the created redirection
[in] fd Existing file descriptor
[in] close_on_exec Whether to close the FD when the process exits
Returns
ProcessError
Definition at line 1067 of file process.c.
process_redirect_to_file()
ProcessError process_redirect_to_file (FileRedirection ** redirection, const char * filepath, int flags, unsigned int mode)
Create a new file redirection for a process.
Parameters
[out] redirection Pointer to store the created redirection
[in] filepath Path to the file
[in] flags File open flags (O_RDONLY, O_WRONLY, O_RDWR, etc.)
[in] mode File mode for creation (if O_CREAT is used)
Returns
ProcessError
Definition at line 1034 of file process.c.
Referenced by process_run_with_file_redirection().
process_run_and_capture()
ProcessError process_run_and_capture (const char * command, const char *const argv[], ProcessOptions * options, int * exit_code)
Run a command and capture its output.
Convenience function that creates a process, captures its output, waits for completion, and cleans up resources.
Parameters
[in] command Path to executable
[in] argv NULL-terminated array of arguments
[in] options Process creation options (NULL for defaults)
[out] exit_code Pointer to receive the exit code (can be NULL)
Returns
PROCESS_SUCCESS on success, error code otherwise
Definition at line 996 of file process.c.
References process_create(), process_free(), and process_wait().
process_run_with_file_redirection()
ProcessError process_run_with_file_redirection (ProcessHandle ** handle, const char * command, const char *const argv[], const char * stdout_file, const char * stderr_file, bool append)
Create a process that redirects its output from stdout and/or stderr to files.
Parameters
[in] handle Pointer to process handle
[in] command Command to run
[in] argv Command arguments
[in] stdout_file File to redirect stdout to, or NULL
[in] stderr_file File to redirect stderr to, or NULL
[in] append Whether to append to files (true) or overwrite (false)
Returns
ProcessError
Create a process that redirects its output from stdout and/or stderr to files.
Parameters
[in] command Command to run
[in] argv Command arguments
[in] stdout_file File to redirect stdout to, or NULL
[in] stderr_file File to redirect stderr to, or NULL
[in] append Whether to append to files (true) or overwrite (false)
Returns
ProcessError
Definition at line 1402 of file process.c.
References process_close_redirection(), process_create_with_redirection(), and process_redirect_to_file().
process_run_with_multiwriter()
ProcessError process_run_with_multiwriter (ProcessResult * result, const char * cmd, const char * args[], int output_fds[], int error_fds[])
Run the command in a process that duplicates output to multiple destinations.
This function sets up a process whose output is duplicated to multiple files/pipes
Parameters
[out] result Will hold process exit information.
[in] cmd Command to execute
[in] argv Arguments (NULL-terminated)
[in] output_fds Array of file descriptors to duplicate output to (NULL-terminated)
[in] error_fds Array of file descriptors to duplicate errors to (NULL-terminated)
Returns
ProcessError
Definition at line 1226 of file process.c.
process_terminate()
ProcessError process_terminate (ProcessHandle * handle, bool force)
Terminate a running process.
Parameters
[in] handle Process handle
[in] force If true, force immediate termination (SIGKILL/TerminateProcess)
Returns
PROCESS_SUCCESS on success, error code otherwise
Definition at line 959 of file process.c.
process_wait()
ProcessError process_wait (ProcessHandle * handle, ProcessResult * result, int timeout_ms)
Wait for a process to complete.
Parameters
[in] handle Process handle
[out] result Pointer to receive exit information (can be NULL)
[in] timeout_ms Timeout in milliseconds (-1 = wait indefinitely)
Returns
PROCESS_SUCCESS on success, error code otherwise
Definition at line 877 of file process.c.
Referenced by process_run_and_capture().